from setuptools import setup, find_packages

setup(
    name="PenphinOS",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        'pyserial',
        'numpy',
        'torch',
        'torchaudio',
        'transformers',
        'python-redmine',
        'python-dotenv',
        'sounddevice',
        'soundfile',
        'opencv-python',
        'pillow',
        'requests',
        'aiohttp',
        'websockets'
    ],
    python_requires='>=3.8',
    author="PenphinOS Team",
    author_email="info@penphin.ai",
    description="Neural operating system for advanced AI interaction",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/penphin/PenphinOS",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
) 